language: php

git:
  depth: 1

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer install -n

script: vendor/bin/phpunit

notifications:
  email: false
