language: php

git:
  depth: 1

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env:
      - LINT=true

  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer install -n
  - composer require satooshi/php-coveralls --dev

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover build/logs/clover
  # Verify coding standard compliance only once
  - if [[ $LINT = true ]]; then
      composer cs-check;
    fi

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email: false
